// Favicon and progressive web app manifest

module.exports = {
  name: 'Ocitocine Starter',
  // Short human-readable name for the application (<12 chars)
  short_name: 'OCTCStarter',
  // General description of what the web application does.
  description: 'Ocitocine Starter',
  // Background color displayed while the css is loading
  background_color: '#FFFFFF',
  theme_color: '#142D75',
  start_url: '.',
  // favicon and pwa icon for android (ios icons and start icon are generated by the favicon plugin)
  icons: {
    // File path from root
    src: 'src/assets/images/Ocitocine.png',
    sizes: [36, 48, 72, 96, 144, 512],
  }
};
